[project]
name = "slackformat"
version = "1.0.0"
description = "A utility for converting between Slack's formats."

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"